matrix:
  include:
  - sudo: required
    language: python
    services:
    - docker
  - os: osx
    osx_image: xcode7.3

notifications:
  email: false

env:
  global:
    - CIBW_BUILD='cp27-* cp35-* cp36-* cp37-*'
    - LD_LIBRARY_PATH="$HOME/build/lib"
    - CIBW_ENVIRONMENT="LD_LIBRARY_PATH=/project/LHAPDF-6.2.1/src/.libs"
    - TWINE_USERNAME=lhapdf
      # Note: TWINE_PASSWORD is set in Travis settings

before_script:
  - wget http://www.hepforge.org/archive/lhapdf/LHAPDF-6.2.1.tar.gz
  - tar xf LHAPDF-6.2.1.tar.gz
  - mkdir build
  - pushd LHAPDF-6.2.1
  # start fix for Python 3.7: redo cython
  - python -m pip install cython
  - pushd wrappers/python
  - cython lhapdf.pyx --cplus
  - popd
  # end fix for Python 3.7
  - ./configure --prefix="$HOME/build"
  - make
  - make install
  - popd

script:
  - python -m pip install git+https://github.com/joerick/cibuildwheel.git
  - cibuildwheel --output-dir wheelhouse
  - python -m pip install twine
  - python -m twine upload wheelhouse/*.whl
